version: "3"
services:
  phpapache:
    container_name: troedelmapDatenbankApache
    build: .
    ports:
      - 8080:80
    depends_on:
      - "db"
    volumes:
      - ./htdocs:/var/www/html
    networks:
      - webnetwork
  db:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "allgemein"
    volumes:
      - ./TroedelmapDatenbank.sql:/docker-entrypoint-initdb.d/prepare.sql
    networks:
      - webnetwork
    
volumes:
  htdocs:

networks:
  webnetwork:
    driver: bridge